// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {inventory} from '../models';

export function AddServer(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<void>;

export function DeleteServer(arg1:number):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetConnectionHistory(arg1:number):Promise<Array<inventory.ConnectionLog>>;

export function GetServer(arg1:number):Promise<inventory.ServerView>;

export function GetServers():Promise<Array<inventory.ServerView>>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScanServer(arg1:number):Promise<void>;

export function ToggleFavorite(arg1:number):Promise<boolean>;
