// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CloseSSHTerminal(arg1) {
  return window['go']['main']['App']['CloseSSHTerminal'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnectionHistory(arg1) {
  return window['go']['main']['App']['GetConnectionHistory'](arg1);
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetTerminalInitialParams() {
  return window['go']['main']['App']['GetTerminalInitialParams']();
}

export function GetTerminalPreference() {
  return window['go']['main']['App']['GetTerminalPreference']();
}

export function OpenStandaloneTerminalWindow(arg1, arg2) {
  return window['go']['main']['App']['OpenStandaloneTerminalWindow'](arg1, arg2);
}

export function ResizeSSHTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSSHTerminal'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveTerminalPreference(arg1) {
  return window['go']['main']['App']['SaveTerminalPreference'](arg1);
}

export function ScanServer(arg1) {
  return window['go']['main']['App']['ScanServer'](arg1);
}

export function SendSSHTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendSSHTerminalInput'](arg1, arg2);
}

export function StartSSHTerminal(arg1) {
  return window['go']['main']['App']['StartSSHTerminal'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}
