// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {inventory} from '../models';
import {main} from '../models';

export function AddServer(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<void>;

export function CloseSSHTerminal(arg1:string):Promise<void>;

export function DeleteServer(arg1:number):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetConnectionHistory(arg1:number):Promise<Array<inventory.ConnectionLog>>;

export function GetServer(arg1:number):Promise<inventory.ServerView>;

export function GetServers():Promise<Array<inventory.ServerView>>;

export function GetTerminalInitialParams():Promise<Record<string, any>>;

export function GetTerminalPreference():Promise<inventory.TerminalPreference>;

export function OpenNativeOSTerminal(arg1:number,arg2:main.SSHConnectionParams):Promise<void>;

export function OpenStandaloneTerminalWindow(arg1:number,arg2:main.SSHConnectionParams):Promise<void>;

export function ResizeSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveTerminalPreference(arg1:inventory.TerminalPreference):Promise<void>;

export function ScanServer(arg1:number):Promise<void>;

export function SendSSHTerminalInput(arg1:string,arg2:string):Promise<void>;

export function StartSSHTerminal(arg1:main.SSHConnectionParams):Promise<string>;

export function TestAPIConnection(arg1:string):Promise<Record<string, any>>;

export function TestDatabaseConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function ToggleFavorite(arg1:number):Promise<boolean>;
