// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnectionHistory(arg1) {
  return window['go']['main']['App']['GetConnectionHistory'](arg1);
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanServer(arg1) {
  return window['go']['main']['App']['ScanServer'](arg1);
}
