name: Snapcraft Promote

on:
  workflow_dispatch:
    inputs:
      from_channel:
        description: 'Source channel (e.g. edge, candidate)'
        required: false
        default: 'edge'
        type: string
      to_channel:
        description: 'Target channel'
        required: true
        type: choice
        options:
          - candidate
          - beta
          - stable
      revision:
        description: 'Snapcraft numeric revision number (optional, e.g. 5 or 12)'
        required: false
        type: string

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Promote Revision
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: |
          if [ -n "${{ github.event.inputs.revision }}" ]; then
            snapcraft promote vpsm --revision=${{ github.event.inputs.revision }} --to-channel=${{ github.event.inputs.to_channel }}
          else
            snapcraft promote vpsm --from-channel=${{ github.event.inputs.from_channel }} --to-channel=${{ github.event.inputs.to_channel }}
          fi
